package com.csye6225.fall2019.model;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="course")
public class Course {
	private String id;
	private String name;
	private String program;
	private String taId;
	private String profId;
	private String createdDate;
	private List<String> students;
	
	public Course() {
	}
	
	public Course(String name, String program, String profId, 
			String taId, String createdDate) {
		this.name = name;
		this.profId = profId;
		this.taId = taId;
		this.program = program;
		this.createdDate = createdDate;
		this.students = new ArrayList<>();
	}
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName="course_id")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName="name")
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	@DynamoDBAttribute(attributeName="students")
	public List<String> getStudents() {
		return students;
	}

	public void setStudents(List<String> students) {
		this.students = students;
	}

	@DynamoDBAttribute(attributeName="program")
	public String getProgram() {
		return program;
	}

	public void setProgram(String program) {
		this.program = program;
	}

	@DynamoDBAttribute(attributeName="ta_id")
	public String getTaId() {
		return taId;
	}

	public void setTaId(String taId) {
		this.taId = taId;
	}

	@DynamoDBAttribute(attributeName="professor_id")
	public String getProfId() {
		return profId;
	}

	public void setProfId(String profId) {
		this.profId = profId;
	}
	
	
	@DynamoDBAttribute(attributeName="created_date")
	public String getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	@DynamoDBIgnore
	@Override
	public String toString() { 
		return "Course{" + "Id=" + this.getId() + ", Name=" + this.getName() + "}";
	}
}
