package com.csye6225.fall2019.model;


import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="professor")
public class Professor{
	private String name;
	private String id;
	private String imageUrl;
	private List<String> teachCourses;
	private String department;
	private String joiningDate;
	
	public Professor() {
	}
	
	public Professor(String name, String department, String date) {
		this.name = name;
		this.department = department;
		this.joiningDate = date;
		this.teachCourses = new ArrayList<>();
	}
	
	@DynamoDBAttribute(attributeName="name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName="professor_id")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName="image_url")
	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@DynamoDBAttribute(attributeName = "teaching_courses")
	public List<String> getTeachCourses() {
		return teachCourses;
	}

	public void setTeachCourses(List<String> teachCourses) {
		this.teachCourses = teachCourses;
	}

	@DynamoDBAttribute(attributeName="department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName="joining_date")
	public String getJoiningDate() {
		return joiningDate;
	}

	public void setJoiningDate(String joiningDate) {
		this.joiningDate = joiningDate;
	}
	
	@DynamoDBIgnore
	@Override
	public String toString() { 
		return "Professor{" + "Id=" + this.getId() + ", Name=" + this.getName()
				+ ", Department=" + this.getDepartment() + ", JoiningDate=" + this.getJoiningDate() + "}";
	}
}
