package com.csye6225.fall2019.model;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="student")
public class Student {
	private String id;
	private String name;
	private String imageUrl;
	private String program;
	private String enrollDate;
	private List<String> enrolledCourses;
	
	public Student() {
	}
	
	public Student(String name, String programId, String date) {
		this.name = name;
		this.program = programId;
		this.enrollDate = date;
		this.enrolledCourses = new ArrayList<>();
	}
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName="student_id")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName="name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute(attributeName="image_url")
	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@DynamoDBAttribute(attributeName = "program")
	public String getProgram() {
		return program;
	}

	public void setProgram(String program) {
		this.program = program;
	}

	@DynamoDBAttribute(attributeName = "enroll_date")
	public String getEnrollDate() {
		return enrollDate;
	}

	public void setEnrollDate(String enrollDate) {
		this.enrollDate = enrollDate;
	}
	
	@DynamoDBAttribute(attributeName = "enrolled_courses")
	public List<String> getEnrolledCourses() {
		return enrolledCourses;
	}

	public void setEnrolledCourses(List<String> enrolledCourses) {
		this.enrolledCourses = enrolledCourses;
	}

	@DynamoDBIgnore
	@Override
	public String toString() { 
		return "Student{" + "Id=" + this.getId() + ", Name=" + this.getName()
				+ ", Program=" + this.getProgram() + ", JoiningDate=" + this.getEnrollDate() + "}";
	}

	
}
